import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "The Royal Shepherd",
    template: "%s | The Royal Shepherd",
  },
  description: "Generated by create next app",
  openGraph: {
    title: "The Royal Shepherd",
    description:
      "This  site is meant to collect all Royal Shepherd member details for necessary documentation and for reference or contact purpose",
    url: "https://rsform-ecru.vercel.app",
    siteName: "The Royal Shepherd",
    images: {
      url: "/rs.jpg",
      width: 1200,
      height: 630,
      alt: "The Royal Shepherd",
    },
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Toaster />
          <div className="flex w-[90%] flex-row mx-auto">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
